language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: htGryOTdar2jy8NUTZUhUwpMujpGAgRrW565lKE2KDtZYQC8n6ZOriJt0UCdQzLfcpHA4W0fUgFrNM+DJhbWHwHneveg9BqzGyC0JZoasvK1m0OnkPGiexR3EGijxZOIsw1fx0gdIWiRlRzbYZ2MAzUVJeBf5EtH3o+qGyaaiYsxlvD6fupqi3HAU/Vn9kaAWX7G0IuD3EPLHc9XFKBfmH5Bo8cgnsDT69c8f/anp6OqcNhuCLRuiQXffXF3kYVl3atyH0UsKe2HDyoIM7NFCZwMjXlvMhuk0AwcptxqgT2rtA743WiiDGPCYgKiY0dbgUmhsiMX/RKutvP5P8X9tjJ0QFvmajP308jsO9/v4aTxjVk8voJ7lMyayWB6gaoVkJauXvlImvBKZk2IO8w6YVnR+3+QQYW44/zCjtTy6q3RgDOv64rq35HHnVpmNQe8vK+vp8jNzyyiNWbIBMOjkACX1Kwdpd+RLFYL0iCttLc8N8U8qjU5m5Yp0XA10fV0/0eJ0GY1gkJIpdhKK2pwfK3nEIK2Guxm2wxNI5/JnTf9fCq4/V+CJijC2FUcK71qdDomHxeSNx2v7iB0VLPrL5y0xPRpxN5iMbAyr5c6HKjeRIdPxsTseM6wNRUKt7lHEBd6d10MPKyfjjgFy/P5riQEibHiyXtw+ANvEvDL+WY=
  file:
    - 'remark-highlight.js'
    - 'remark-highlight.min.js'
  on:
    tags: true
